#version=1.5
include:
   - local: '/ci_templates/default_catkin_project.yml'

code_quality:
  before_script: []
  script:
  - ls

cmake_format:
  # check for formatting issues in cmake files
  stage: test
  dependencies: []
  only: [master, merge_requests]
  cache: {}
  variables:
    GIT_STRATEGY: fetch
  before_script: []
  script:
    - sudo apt update && sudo apt install -y python3-pip && pip3 install --user cmake_format pyyaml
    - env PATH=~/.local/bin:$PATH find . -name "*.cmake" -exec cmake-format -i {} +
    - git diff --exit-code || (echo "CMake formatting issues found. Please fix them first!"; $(exit 1))

deps:
  script:
  # test only a few dependencies. There are too many
  - mrt ci test_deps -f --no-status --release -i example_package_ros_tool --only $CI_PROJECT_NAME
