#version=1.5
include:
   - local: '/ci_templates/default_catkin_project.yml'

code_quality:
  before_script: []
  script:
  - ls

deps:
  script:
  # test only a few dependencies. There are too many
  - mrt ci test_deps -f --no-status --release -i example_package_ros_tool --only $CI_PROJECT_NAME
