variables:
  GIT_STRATEGY: none
# Cache build results between building and testing
cache:
  paths:
  - catkin_ws/
stages:
  - build
  - test
  - deploy
  - deps

# Prepare workspace and checkout the code. This will be executed before every stage
before_script:
  # Environment variablen setzen
  - export SHELL="/bin/bash"
  # Prepare workspace (in folder catkin_ws)
  - sudo apt-get update
  - mrt ci prepare $CI_PROJECT_NAME -c $CI_COMMIT_SHA
  - cd catkin_ws
  # add current branch name to branch management
  - mrt ws branches add $CI_COMMIT_REF_NAME

build:
  stage: build
  script:
  # Build project and resolve deps at the same time in debug mode
  - mrt catkin build -s -rd -c --debug --default_yes --no-status $CI_PROJECT_NAME
  # generate documentation
  - mrt doc build --no-deps $CI_PROJECT_NAME
  - cp -r build_debug/$CI_PROJECT_NAME/doxygen_doc/html ../doxygen
  # make doxygen documentation available in gitlab
  artifacts:
    name: doxygen
    paths:
    - doxygen
    expire_in: 6 mos

general_code_quality:
  stage: build
  image: docker:stable
  before_script: []
  cache: {}
  variables:
    DOCKER_DRIVER: overlay2
    GIT_STRATEGY: fetch
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
    - chmod a+rw gl-code-quality-report.json
  artifacts:
    paths: [gl-code-quality-report.json]

code_quality:
  dependencies:
    - general_code_quality
  stage: test
  only:
  - master
  - merge_request
  allow_failure: true
  artifacts:
    paths: [gl-code-quality-report.json]
  script:
  # Build code again, in case caching didn't work
  - mrt catkin build -s -rd --debug --default_yes --no-status $CI_PROJECT_NAME
  - source devel_debug/setup.bash
  - cd src/$CI_PROJECT_NAME
  - rm codeclimate.json || true
  - cp ../../../gl-code-quality-report.json codeclimate.json || true
  - mrt ci codequality $CI_PROJECT_NAME --yes
  - cp codeclimate.json ../../../gl-code-quality-report.json

check_code_quality:
  dependencies:
    - code_quality
  stage: deploy
  only:
  - master
  - merge_request
  # default filename is codeclimate.json
  script: mrt ci validate_codequality $MRT_QUALITY_LEVEL --filename gl-code-quality-report.json
  before_script: []
  cache: {}

test:
  stage: test
  coverage: '/lines: \d+.\d+\%/'
  variables:
    MRT_MIN_COVERAGE: $MRT_REQUIRED_COVERAGE
  script:
  # Build code again, in case caching didn't work
  - mrt catkin build -s -rd --debug --default_yes --no-status $CI_PROJECT_NAME
  # Run tests
  - source devel_debug/setup.bash
  - mrt catkin run_tests --no-status $CI_PROJECT_NAME --no-deps
  # Summarize results
  - catkin_test_results --verbose build_debug/$CI_PROJECT_NAME
  - cp -r build_debug/$CI_PROJECT_NAME/coverage .. || true
  # make coverage information available in gitlab
  artifacts:
    name: coverage
    paths:
    - coverage
    expire_in: 6 mos
    reports:
      junit: catkin_ws/build_debug/$CI_PROJECT_NAME/test_results/$CI_PROJECT_NAME/*.xml

report_licenses:
  stage: build
  only:
  - master
  - merge_request
  script:
  - mrt ci
  - mrt ci report_licenses .

# This job will create a homepage for your project, where you can browse coverage and doxygen.
# It is avaliable under <namespace>.pages.mrt.uni-karlsruhe.de/<pkg_name>/<doxygen/coverage>/index.html
pages:
  before_script: []
  stage: deploy
  script:
  # everything in the public folder will be available as website
  - mkdir public
  - cp -r coverage public/ || true
  - cp -r doxygen public/
  artifacts:
    paths:
    - public
  only:
  # only execute for master branch
  - master

deps:
  stage: deps
  variables:
    MRT_CI_NO_TIDY: 1
  cache:
    paths:
    - catkin_ws/
    key: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-deps
  only:
  # only execute if this is the master branch
  - master
  - merge_request
  script:
  # test all dependencies of this package. Exclude packages with -e, include with -i.
  - mrt ci test_deps -f --no-status --release $CI_PROJECT_NAME
