find_package(CUDA REQUIRED)

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.9.0")
    set(CMAKE_CUDA_COMPILER "${CUDA_TOOLKIT_ROOT_DIR}/bin/nvcc")
    set(CMAKE_CUDA_FLAGS "-lineinfo")
    set(CMAKE_CUDA_HOST_COMPILER "g++-7")

    enable_language(CUDA)

    if(NOT DEFINED CMAKE_CUDA_STANDARD)
        set(CMAKE_CUDA_STANDARD 14)
        set(CMAKE_CUDA_STANDARD_REQUIRED ON)
    endif()

    set(CUDA_INCLUDE_DIRS "${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")
endif()
