set(PACKAGE_HEADER_FILES "ANN/ANN.h")
set(PACKAGE_LIBRARIES ANN ann)
set(PACKAGE_LOCAL_PATH "/mrtsoftware/pkg/local/ann-1.1.2")
set(PACKAGE_PATH "/mrtsoftware/pkg/ann-1.1.2")

find_path(ANN_INCLUDE_DIR NAMES ${PACKAGE_HEADER_FILES} PATHS "${PACKAGE_LOCAL_PATH}/include" "${PACKAGE_PATH}/include")
find_library(ANN_LIBRARIES NAMES ${PACKAGE_LIBRARIES} PATHS "${PACKAGE_LOCAL_PATH}/lib" "${PACKAGE_PATH}/lib")

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ANN FOUND_VAR ANN_FOUND REQUIRED_VARS ANN_INCLUDE_DIR ANN_LIBRARIES)

