set(PACKAGE_HEADER_FILES metis.h)
set(PACKAGE_LIBRARIES metis)

find_path(Metis_INCLUDE_DIR NAMES ${PACKAGE_HEADER_FILES})
find_library(Metis_LIBRARIES NAMES ${PACKAGE_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Metis FOUND_VAR Metis_FOUND REQUIRED_VARS Metis_INCLUDE_DIR Metis_LIBRARIES)

